[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  external_node_modules = ["sharp"]

# Force form processing
[build.environment]
  NETLIFY_FORMS_DETECT = "true"

# Explicit form configuration
[[forms]]
  name = "contact"
  action = "/thank-you"
  
  [[forms.fields]]
    name = "name"
    type = "text"
    
  [[forms.fields]]
    name = "email" 
    type = "email"
    
  [[forms.fields]]
    name = "phone"
    type = "tel"
    
  [[forms.fields]]
    name = "message"
    type = "textarea"
    
  [[forms.fields]]
    name = "attachment"
    type = "file" 