[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  external_node_modules = ["sharp"]

# Form notifications
[[forms]]
  name = "contact"
  
  [[forms.notifications]]
  type = "email"
  event = "submission"
  to = "admin@klubhousetherapyservices.com" 