[build]
  command = "npm run build"
  publish = ".next"

# Force rebuild to detect all Netlify forms - 2025-01-27

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  external_node_modules = ["sharp"]

# Form handling settings
[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

# Environment variables for production
[context.production.environment]
  NEXT_PUBLIC_DOMAIN = "klubhousetherapyservices.com"

# Environment variables for deploy previews
[context.deploy-preview.environment]
  NEXT_PUBLIC_DOMAIN = "klubhousetherapyservices.com" 