[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  external_node_modules = ["sharp"]

# Force form processing
[build.environment]
  NETLIFY_FORMS_DETECT = "true"

# Form settings will be handled by Netlify's automatic detection 